//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace locationservice.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int id { get; set; }
        public string X { get; set; }
        public string Y { get; set; }
        public string time { get; set; }
        public string message { get; set; }
        public System.DateTime uploadtime { get; set; }
    }
}
